# selecting alpine based image as it is smaller in size hence preferred for production
FROM nginx:1.29.4-alpine

# Always see destination copy path in documents
COPY index.html /usr/share/nginx/html

EXPOSE 80
